export * from "./AboutMeSection";
export * from "./ContactPersonSection";
export * from "./HeroSection";
export * from "./PersonalPhilosophySection";
export * from "./ProcessSection";
export * from "./ProjectSection";
export * from "./SkillSection";
export * from "./WhyWorkMeSection";
export * from "./FooterTaglineSection";
